-- ========================================
-- INSERTAR TAREAS PREDEFINIDAS EN CHECKLIST
-- ========================================
-- Ejecuta esto en Supabase SQL Editor

-- PASO 1: Insertar tareas de Limpieza Regular para HYNTIBA2 APTO 406
INSERT INTO checklist (house, item, room, complete, assigned_to) VALUES
('HYNTIBA2 APTO 406', 'Barrer y trapear toda la casa.', 'ENTRADA', false, null),
('HYNTIBA2 APTO 406', 'Quitar el polvo de todas las superficies y decoración usando un trapo húmedo.', 'ENTRADA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar los televisores cuidadosamente sin dejar marcas en la pantalla.', 'ENTRADA', false, null),
('HYNTIBA2 APTO 406', 'Revisar zócalos y esquinas para asegurarse de que estén limpios.', 'ENTRADA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar telaraña.', 'ENTRADA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar todas las superficies de la sala.', 'SALA', false, null),
('HYNTIBA2 APTO 406', 'Mover los cojines del sofá y verificar que no haya suciedad ni hormigas debajo.', 'SALA', false, null),
('HYNTIBA2 APTO 406', 'Organizar cojines y dejar la sala ordenada.', 'SALA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar mesa, sillas y superficies del comedor.', 'COMEDOR', false, null),
('HYNTIBA2 APTO 406', 'Asegurarse de que el área del comedor quede limpia y ordenada.', 'COMEDOR', false, null),
('HYNTIBA2 APTO 406', 'Limpiar superficies, gabinetes por fuera y por dentro de la cocina.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Verificar que los gabinetes estén limpios, organizados y funcionales.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar la cafetera y su filtro.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Verificar que el dispensador de jabón de loza esté lleno.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Dejar toallas de cocina limpias y disponibles para los visitantes.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar microondas por dentro y por fuera.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar el filtro de agua.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar la nevera por dentro y por fuera (no dejar alimentos).', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Lavar las canecas de basura y colocar bolsas nuevas.', 'COCINA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar ducha (pisos y paredes) de los baños.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Limpiar divisiones de vidrio y asegurarse de que no queden marcas.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Limpiar espejo, sanitario y lavamanos con Clorox.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Lavar las canecas de basura y colocar bolsas nuevas en los baños.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Verificar disponibilidad de toallas: máximo 10 toallas blancas de cuerpo en toda la casa, máximo 4 toallas de mano en total.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Dejar un rollo de papel higiénico nuevo instalado en cada baño.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Dejar un rollo extra en el cuarto de lavado.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Lavar y volver a colocar los tapetes de baño.', 'BAÑOS', false, null),
('HYNTIBA2 APTO 406', 'Revisar que no haya objetos dentro de los cajones de las habitaciones.', 'HABITACIONES', false, null),
('HYNTIBA2 APTO 406', 'Lavar sábanas y hacer las camas correctamente.', 'HABITACIONES', false, null),
('HYNTIBA2 APTO 406', 'Limpiar el polvo de todas las superficies de las habitaciones.', 'HABITACIONES', false, null),
('HYNTIBA2 APTO 406', 'Lavar los tapetes de la habitación y volver a colocarlos limpios.', 'HABITACIONES', false, null),
('HYNTIBA2 APTO 406', 'Limpiar el filtro de la lavadora en cada lavada.', 'ZONA DE LAVADO', false, null),
('HYNTIBA2 APTO 406', 'Limpiar el gabinete debajo del lavadero.', 'ZONA DE LAVADO', false, null),
('HYNTIBA2 APTO 406', 'Dejar ganchos de ropa disponibles.', 'ZONA DE LAVADO', false, null),
('HYNTIBA2 APTO 406', 'Dejar toallas disponibles para la piscina.', 'ZONA DE LAVADO', false, null),
('HYNTIBA2 APTO 406', 'Barrer y trapear el área de BBQ.', 'ÁREA DE BBQ', false, null),
('HYNTIBA2 APTO 406', 'Limpiar mesa y superficies del área de BBQ.', 'ÁREA DE BBQ', false, null),
('HYNTIBA2 APTO 406', 'Limpiar la mini nevera y no dejar ningún alimento dentro.', 'ÁREA DE BBQ', false, null),
('HYNTIBA2 APTO 406', 'Limpiar la parrilla con el cepillo (no usar agua).', 'ÁREA DE BBQ', false, null),
('HYNTIBA2 APTO 406', 'Retirar las cenizas del carbón.', 'ÁREA DE BBQ', false, null),
('HYNTIBA2 APTO 406', 'Dejar toda el área de BBQ limpia y ordenada.', 'ÁREA DE BBQ', false, null),
('HYNTIBA2 APTO 406', 'Barrer y trapear el área de piscina.', 'ÁREA DE PISCINA', false, null),
('HYNTIBA2 APTO 406', 'Organizar los muebles alrededor de la piscina.', 'ÁREA DE PISCINA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar el piso de la terraza.', 'TERRAZA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar superficies de la terraza.', 'TERRAZA', false, null),
('HYNTIBA2 APTO 406', 'Organizar los cojines de la sala exterior.', 'TERRAZA', false, null);

-- PASO 2: Insertar tareas de Limpieza Profunda
INSERT INTO checklist (house, item, room, complete, assigned_to) VALUES
('HYNTIBA2 APTO 406', 'Lavar los forros de los muebles (sofás, sillas y cojines).', 'LIMPIEZA PROFUNDA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar todas las ventanas y ventanales de la casa, por dentro y por fuera.', 'LIMPIEZA PROFUNDA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar con hidrolavadora el piso exterior, incluyendo escaleras, terraza y placas vehiculares.', 'LIMPIEZA PROFUNDA', false, null),
('HYNTIBA2 APTO 406', 'Lavar la caneca grande de basura ubicada debajo de la escalera.', 'LIMPIEZA PROFUNDA', false, null),
('HYNTIBA2 APTO 406', 'Limpiar las paredes y los guardaescobas de toda la casa.', 'LIMPIEZA PROFUNDA', false, null);

-- PASO 3: Insertar tareas de Mantenimiento
INSERT INTO checklist (house, item, room, complete, assigned_to) VALUES
('HYNTIBA2 APTO 406', 'Mantener la piscina limpia y en funcionamiento.', 'PISCINA Y AGUA', false, null),
('HYNTIBA2 APTO 406', 'Revisar constantemente el cuarto de máquinas para verificar su funcionamiento y detectar posibles filtraciones de agua.', 'PISCINA Y AGUA', false, null),
('HYNTIBA2 APTO 406', 'Chequear que el generador eléctrico funcione correctamente y tenga diesel suficiente.', 'SISTEMAS ELÉCTRICOS', false, null),
('HYNTIBA2 APTO 406', 'Encender la planta eléctrica al menos 2 veces al mes durante mínimo media hora.', 'SISTEMAS ELÉCTRICOS', false, null),
('HYNTIBA2 APTO 406', 'Cortar el césped cada mes y medio a dos meses, y limpiar restos de césped.', 'ÁREAS VERDES', false, null),
('HYNTIBA2 APTO 406', 'Mantenimiento de palmeras: remover hojas secas.', 'ÁREAS VERDES', false, null),
('HYNTIBA2 APTO 406', 'Mantener la matera de la terraza libre de maleza y deshierbar regularmente.', 'ÁREAS VERDES', false, null),
('HYNTIBA2 APTO 406', 'Regar las plantas vivas según necesidad.', 'ÁREAS VERDES', false, null);

-- Hacer lo mismo para EPIC D1
INSERT INTO checklist (house, item, room, complete, assigned_to) VALUES
('EPIC D1', 'Barrer y trapear toda la casa.', 'ENTRADA', false, null),
('EPIC D1', 'Quitar el polvo de todas las superficies y decoración usando un trapo húmedo.', 'ENTRADA', false, null),
('EPIC D1', 'Limpiar los televisores cuidadosamente sin dejar marcas en la pantalla.', 'ENTRADA', false, null),
('EPIC D1', 'Revisar zócalos y esquinas para asegurarse de que estén limpios.', 'ENTRADA', false, null),
('EPIC D1', 'Limpiar telaraña.', 'ENTRADA', false, null),
('EPIC D1', 'Limpiar todas las superficies de la sala.', 'SALA', false, null),
('EPIC D1', 'Mover los cojines del sofá y verificar que no haya suciedad ni hormigas debajo.', 'SALA', false, null),
('EPIC D1', 'Organizar cojines y dejar la sala ordenada.', 'SALA', false, null),
('EPIC D1', 'Limpiar mesa, sillas y superficies del comedor.', 'COMEDOR', false, null),
('EPIC D1', 'Asegurarse de que el área del comedor quede limpia y ordenada.', 'COMEDOR', false, null),
('EPIC D1', 'Limpiar superficies, gabinetes por fuera y por dentro de la cocina.', 'COCINA', false, null),
('EPIC D1', 'Verificar que los gabinetes estén limpios, organizados y funcionales.', 'COCINA', false, null),
('EPIC D1', 'Limpiar la cafetera y su filtro.', 'COCINA', false, null),
('EPIC D1', 'Verificar que el dispensador de jabón de loza esté lleno.', 'COCINA', false, null),
('EPIC D1', 'Dejar toallas de cocina limpias y disponibles para los visitantes.', 'COCINA', false, null),
('EPIC D1', 'Limpiar microondas por dentro y por fuera.', 'COCINA', false, null),
('EPIC D1', 'Limpiar el filtro de agua.', 'COCINA', false, null),
('EPIC D1', 'Limpiar la nevera por dentro y por fuera (no dejar alimentos).', 'COCINA', false, null),
('EPIC D1', 'Lavar las canecas de basura y colocar bolsas nuevas.', 'COCINA', false, null),
('EPIC D1', 'Limpiar ducha (pisos y paredes) de los baños.', 'BAÑOS', false, null),
('EPIC D1', 'Limpiar divisiones de vidrio y asegurarse de que no queden marcas.', 'BAÑOS', false, null),
('EPIC D1', 'Limpiar espejo, sanitario y lavamanos con Clorox.', 'BAÑOS', false, null),
('EPIC D1', 'Lavar las canecas de basura y colocar bolsas nuevas en los baños.', 'BAÑOS', false, null),
('EPIC D1', 'Verificar disponibilidad de toallas: máximo 10 toallas blancas de cuerpo en toda la casa, máximo 4 toallas de mano en total.', 'BAÑOS', false, null),
('EPIC D1', 'Dejar un rollo de papel higiénico nuevo instalado en cada baño.', 'BAÑOS', false, null),
('EPIC D1', 'Dejar un rollo extra en el cuarto de lavado.', 'BAÑOS', false, null),
('EPIC D1', 'Lavar y volver a colocar los tapetes de baño.', 'BAÑOS', false, null),
('EPIC D1', 'Revisar que no haya objetos dentro de los cajones de las habitaciones.', 'HABITACIONES', false, null),
('EPIC D1', 'Lavar sábanas y hacer las camas correctamente.', 'HABITACIONES', false, null),
('EPIC D1', 'Limpiar el polvo de todas las superficies de las habitaciones.', 'HABITACIONES', false, null),
('EPIC D1', 'Lavar los tapetes de la habitación y volver a colocarlos limpios.', 'HABITACIONES', false, null),
('EPIC D1', 'Limpiar el filtro de la lavadora en cada lavada.', 'ZONA DE LAVADO', false, null),
('EPIC D1', 'Limpiar el gabinete debajo del lavadero.', 'ZONA DE LAVADO', false, null),
('EPIC D1', 'Dejar ganchos de ropa disponibles.', 'ZONA DE LAVADO', false, null),
('EPIC D1', 'Dejar toallas disponibles para la piscina.', 'ZONA DE LAVADO', false, null),
('EPIC D1', 'Barrer y trapear el área de BBQ.', 'ÁREA DE BBQ', false, null),
('EPIC D1', 'Limpiar mesa y superficies del área de BBQ.', 'ÁREA DE BBQ', false, null),
('EPIC D1', 'Limpiar la mini nevera y no dejar ningún alimento dentro.', 'ÁREA DE BBQ', false, null),
('EPIC D1', 'Limpiar la parrilla con el cepillo (no usar agua).', 'ÁREA DE BBQ', false, null),
('EPIC D1', 'Retirar las cenizas del carbón.', 'ÁREA DE BBQ', false, null),
('EPIC D1', 'Dejar toda el área de BBQ limpia y ordenada.', 'ÁREA DE BBQ', false, null),
('EPIC D1', 'Barrer y trapear el área de piscina.', 'ÁREA DE PISCINA', false, null),
('EPIC D1', 'Organizar los muebles alrededor de la piscina.', 'ÁREA DE PISCINA', false, null),
('EPIC D1', 'Limpiar el piso de la terraza.', 'TERRAZA', false, null),
('EPIC D1', 'Limpiar superficies de la terraza.', 'TERRAZA', false, null),
('EPIC D1', 'Organizar los cojines de la sala exterior.', 'TERRAZA', false, null),
('EPIC D1', 'Lavar los forros de los muebles (sofás, sillas y cojines).', 'LIMPIEZA PROFUNDA', false, null),
('EPIC D1', 'Limpiar todas las ventanas y ventanales de la casa, por dentro y por fuera.', 'LIMPIEZA PROFUNDA', false, null),
('EPIC D1', 'Limpiar con hidrolavadora el piso exterior, incluyendo escaleras, terraza y placas vehiculares.', 'LIMPIEZA PROFUNDA', false, null),
('EPIC D1', 'Lavar la caneca grande de basura ubicada debajo de la escalera.', 'LIMPIEZA PROFUNDA', false, null),
('EPIC D1', 'Limpiar las paredes y los guardaescobas de toda la casa.', 'LIMPIEZA PROFUNDA', false, null),
('EPIC D1', 'Mantener la piscina limpia y en funcionamiento.', 'PISCINA Y AGUA', false, null),
('EPIC D1', 'Revisar constantemente el cuarto de máquinas para verificar su funcionamiento y detectar posibles filtraciones de agua.', 'PISCINA Y AGUA', false, null),
('EPIC D1', 'Chequear que el generador eléctrico funcione correctamente y tenga diesel suficiente.', 'SISTEMAS ELÉCTRICOS', false, null),
('EPIC D1', 'Encender la planta eléctrica al menos 2 veces al mes durante mínimo media hora.', 'SISTEMAS ELÉCTRICOS', false, null),
('EPIC D1', 'Cortar el césped cada mes y medio a dos meses, y limpiar restos de césped.', 'ÁREAS VERDES', false, null),
('EPIC D1', 'Mantenimiento de palmeras: remover hojas secas.', 'ÁREAS VERDES', false, null),
('EPIC D1', 'Mantener la matera de la terraza libre de maleza y deshierbar regularmente.', 'ÁREAS VERDES', false, null),
('EPIC D1', 'Regar las plantas vivas según necesidad.', 'ÁREAS VERDES', false, null);

-- Verificar
SELECT house, COUNT(*) as total_tareas FROM checklist GROUP BY house;
