-- Seed inventory_templates for EPIC D1 (run once)
-- Assumes inventory_templates table exists with columns:
-- house, item_name, quantity, category, location, order_num, active

insert into inventory_templates (house, item_name, quantity, category, location, order_num, active)
values
('EPIC D1','Platos llanos',12,'Cocina','Cocina',1,true),
('EPIC D1','Platos hondos',12,'Cocina','Cocina',2,true),
('EPIC D1','Vasos altos (agua/jugo)',15,'Cocina','Cocina',3,true),
('EPIC D1','Vasos para cerveza',10,'Cocina','Cocina',4,true),
('EPIC D1','Copas para vino',10,'Cocina','Cocina',5,true),
('EPIC D1','Tazas para café/té',12,'Cocina','Cocina',6,true),
('EPIC D1','Cubiertos (tenedores)',12,'Cocina','Cocina',7,true),
('EPIC D1','Cubiertos (cucharas soperas)',12,'Cocina','Cocina',8,true),
('EPIC D1','Cubiertos (cucharas de postre)',12,'Cocina','Cocina',9,true),
('EPIC D1','Cubiertos (cuchillos de mesa)',12,'Cocina','Cocina',10,true),
('EPIC D1','Cuchillos de cocina (set)',5,'Cocina','Cocina',11,true),
('EPIC D1','Tablas de picar',3,'Cocina','Cocina',12,true),
('EPIC D1','Ollas medianas/grandes',5,'Cocina','Cocina',13,true),
('EPIC D1','Sartenes (incluyendo antiadherente grande)',4,'Cocina','Cocina',14,true),
('EPIC D1','Licuadora',1,'Cocina','Cocina',15,true),
('EPIC D1','Cafetera eléctrica',1,'Cocina','Cocina',16,true),
('EPIC D1','Hervidor eléctrico',1,'Cocina','Cocina',17,true),
('EPIC D1','Microondas',1,'Cocina','Cocina',18,true),
('EPIC D1','Toallas de cocina',10,'Cocina','Cocina',19,true),
('EPIC D1','Trapos de cocina',8,'Cocina','Cocina',20,true),
('EPIC D1','Detergente para platos',2,'Cocina','Cocina',21,true),
('EPIC D1','Esponjas',6,'Cocina','Cocina',22,true),
('EPIC D1','Bolsas de basura',50,'Cocina','Cocina',23,true),
('EPIC D1','Papel aluminio',2,'Cocina','Cocina',24,true),
('EPIC D1','Film plástico',2,'Cocina','Cocina',25,true),
('EPIC D1','Servilletas de papel',2,'Cocina','Cocina',26,true),
('EPIC D1','Sal, azúcar, aceite (paquete inicial)',1,'Cocina','Cocina',27,true),

('EPIC D1','Controles remoto (TV + A/C o ventilador)',2,'Sala-Comedor','Sala-Comedor',28,true),
('EPIC D1','Cojines para sofá',10,'Sala-Comedor','Sala-Comedor',29,true),
('EPIC D1','Mantas ligeras',4,'Sala-Comedor','Sala-Comedor',30,true),
('EPIC D1','Sillas comedor + extras',12,'Sala-Comedor','Sala-Comedor',31,true),
('EPIC D1','Posavasos',12,'Sala-Comedor','Sala-Comedor',32,true),

('EPIC D1','Sets de sábanas completos',12,'Dormitorios','Dormitorios',33,true),
('EPIC D1','Almohadas',20,'Dormitorios','Dormitorios',34,true),
('EPIC D1','Fundas de almohada',24,'Dormitorios','Dormitorios',35,true),
('EPIC D1','Cobijas o edredones',10,'Dormitorios','Dormitorios',36,true),
('EPIC D1','Perchas',60,'Dormitorios','Dormitorios',37,true),
('EPIC D1','Lámparas de mesa de noche',4,'Dormitorios','Dormitorios',38,true),

('EPIC D1','Toallas grandes (baño)',16,'Baños','Baños',39,true),
('EPIC D1','Toallas medianas (mano)',12,'Baños','Baños',40,true),
('EPIC D1','Toallas pequeñas (cara)',10,'Baños','Baños',41,true),
('EPIC D1','Tapetes de baño',4,'Baños','Baños',42,true),
('EPIC D1','Jabón líquido manos/baño',4,'Baños','Baños',43,true),
('EPIC D1','Papel higiénico',24,'Baños','Baños',44,true),
('EPIC D1','Secador de pelo',3,'Baños','Baños',45,true),
('EPIC D1','Basureros con tapa',4,'Baños','Baños',46,true),

('EPIC D1','Detergente para ropa',2,'Zona de lavado','Zona de lavado',47,true),
('EPIC D1','Suavizante',1,'Zona de lavado','Zona de lavado',48,true),
('EPIC D1','Cesto ropa sucia',2,'Zona de lavado','Zona de lavado',49,true),
('EPIC D1','Plancha',1,'Zona de lavado','Zona de lavado',50,true),
('EPIC D1','Tabla de planchar',1,'Zona de lavado','Zona de lavado',51,true),

('EPIC D1','Toallas para piscina/exterior',15,'Piscina y Jacuzzi','Piscina y Jacuzzi',52,true),
('EPIC D1','Flotadores/inflables',6,'Piscina y Jacuzzi','Piscina y Jacuzzi',53,true),
('EPIC D1','Sillas o tumbonas exteriores',10,'Piscina y Jacuzzi','Piscina y Jacuzzi',54,true),
('EPIC D1','Sombrillas o toldos',3,'Piscina y Jacuzzi','Piscina y Jacuzzi',55,true),
('EPIC D1','Red recogehojas piscina',1,'Piscina y Jacuzzi','Piscina y Jacuzzi',56,true),
('EPIC D1','Cepillo/barredor piscina',1,'Piscina y Jacuzzi','Piscina y Jacuzzi',57,true),

('EPIC D1','Parrilla/gas o carbón',1,'Zona BBQ y Terraza','Zona BBQ y Terraza',58,true),
('EPIC D1','Pinzas/utensilios BBQ (set)',4,'Zona BBQ y Terraza','Zona BBQ y Terraza',59,true),
('EPIC D1','Mesa exterior + sillas',10,'Zona BBQ y Terraza','Zona BBQ y Terraza',60,true),
('EPIC D1','Basurero exterior con tapa',2,'Zona BBQ y Terraza','Zona BBQ y Terraza',61,true),
('EPIC D1','Cenicero (exterior)',2,'Zona BBQ y Terraza','Zona BBQ y Terraza',62,true),

('EPIC D1','Botiquín primeros auxilios',1,'Seguridad y General','Seguridad y General',63,true),
('EPIC D1','Extintor',1,'Seguridad y General','Seguridad y General',64,true),
('EPIC D1','Linterna',2,'Seguridad y General','Seguridad y General',65,true),
('EPIC D1','Manual casa + wifi contraseña',1,'Seguridad y General','Seguridad y General',66,true),
('EPIC D1','Repelente mosquitos',2,'Seguridad y General','Seguridad y General',67,true),
('EPIC D1','Cargadores USB',4,'Seguridad y General','Seguridad y General',68,true);
