-- ========================================
-- CONFIGURACIÓN DE TABLA CALENDAR_ASSIGNMENTS
-- ========================================

DROP INDEX IF EXISTS idx_calendar_house CASCADE;
DROP INDEX IF EXISTS idx_calendar_employee CASCADE;
DROP INDEX IF EXISTS idx_calendar_house_employee CASCADE;

DROP TABLE IF EXISTS calendar_assignments CASCADE;

CREATE TABLE calendar_assignments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  house TEXT NOT NULL,
  employee TEXT NOT NULL,
  date DATE NOT NULL,
  time TIME,
  type TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  completed_by TEXT DEFAULT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_calendar_house ON calendar_assignments(house);
CREATE INDEX idx_calendar_employee ON calendar_assignments(employee);
CREATE INDEX idx_calendar_house_employee ON calendar_assignments(house, employee);
CREATE INDEX idx_calendar_date ON calendar_assignments(date);

ALTER TABLE calendar_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "allow_select_calendar" ON calendar_assignments;
DROP POLICY IF EXISTS "allow_insert_calendar" ON calendar_assignments;
DROP POLICY IF EXISTS "allow_update_calendar" ON calendar_assignments;
DROP POLICY IF EXISTS "allow_delete_calendar" ON calendar_assignments;

CREATE POLICY "allow_select_calendar" ON calendar_assignments
  FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "allow_insert_calendar" ON calendar_assignments
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "allow_update_calendar" ON calendar_assignments
  FOR UPDATE USING (auth.role() = 'authenticated') 
  WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "allow_delete_calendar" ON calendar_assignments
  FOR DELETE USING (auth.role() = 'authenticated');

SELECT 'Tabla calendar_assignments configurada' as status, COUNT(*) as registros FROM calendar_assignments;
