-- ========================================
-- CONFIGURACIÓN DE TABLA CHECKLIST EN SUPABASE
-- ========================================
-- Ejecuta este SQL en el editor SQL de Supabase (https://supabase.com/dashboard/)
-- 
-- IMPORTANTE: Este script DESHABILITA RLS para que funcione correctamente
-- Si necesitas RLS después, puedes habilitarlo manualmente

-- Paso 1: CREAR LA TABLA (si no existe)
CREATE TABLE IF NOT EXISTS checklist (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  house TEXT NOT NULL,
  item TEXT NOT NULL,
  room TEXT,
  complete BOOLEAN DEFAULT FALSE,
  assigned_to TEXT DEFAULT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Paso 2: DESHABILITAR RLS (permite que cualquiera acceda)
-- Si necesitas seguridad después, puedes reconfigurar esto
ALTER TABLE checklist DISABLE ROW LEVEL SECURITY;

-- Paso 3: CREAR ÍNDICES PARA PERFORMANCE
DROP INDEX IF EXISTS idx_checklist_house;
DROP INDEX IF EXISTS idx_checklist_house_complete;

CREATE INDEX idx_checklist_house ON checklist(house);
CREATE INDEX idx_checklist_house_complete ON checklist(house, complete);

-- Paso 4: ELIMINAR POLÍTICAS RLS ANTERIORES (si existen)
DROP POLICY IF EXISTS "Users can select checklist items" ON checklist;
DROP POLICY IF EXISTS "Managers can insert checklist items" ON checklist;
DROP POLICY IF EXISTS "Users can update checklist items" ON checklist;
DROP POLICY IF EXISTS "Managers can delete checklist items" ON checklist;

-- Paso 5: VERIFICAR QUE TODO ESTÁ CONFIGURADO
SELECT 
  'Tabla checklist lista' as status,
  COUNT(*) as registros_actuales
FROM checklist;

-- Listo! Ahora intenta agregar una tarea en el Dashboard
-- Las tareas deberían guardarse sin problemas de RLS
