-- ========================================
-- CONFIGURACIÓN FINAL DE TABLA CHECKLIST
-- ========================================
-- Ejecuta TODOS estos comandos en Supabase SQL Editor

-- PASO 1: Crear tabla
DROP TABLE IF EXISTS checklist CASCADE;

CREATE TABLE checklist (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  house TEXT NOT NULL,
  item TEXT NOT NULL,
  room TEXT,
  complete BOOLEAN DEFAULT FALSE,
  assigned_to TEXT DEFAULT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- PASO 2: Crear índices
CREATE INDEX idx_checklist_house ON checklist(house);
CREATE INDEX idx_checklist_house_complete ON checklist(house, complete);
CREATE INDEX idx_checklist_created_at ON checklist(created_at);

-- PASO 3: HABILITAR RLS (es necesario para la autenticación)
ALTER TABLE checklist ENABLE ROW LEVEL SECURITY;

-- PASO 4: ELIMINAR políticas anteriores
DROP POLICY IF EXISTS "allow_select" ON checklist;
DROP POLICY IF EXISTS "allow_insert" ON checklist;
DROP POLICY IF EXISTS "allow_update" ON checklist;
DROP POLICY IF EXISTS "allow_delete" ON checklist;
DROP POLICY IF EXISTS "Users can select checklist items" ON checklist;
DROP POLICY IF EXISTS "Managers can insert checklist items" ON checklist;
DROP POLICY IF EXISTS "Users can update checklist items" ON checklist;
DROP POLICY IF EXISTS "Managers can delete checklist items" ON checklist;

-- PASO 5: CREAR POLÍTICAS RLS PERMISIVAS
-- Política SELECT: Todos los usuarios autenticados pueden ver
CREATE POLICY "allow_select" ON checklist
  FOR SELECT USING (auth.role() = 'authenticated');

-- Política INSERT: Todos los usuarios autenticados pueden insertar
CREATE POLICY "allow_insert" ON checklist
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Política UPDATE: Todos los usuarios autenticados pueden actualizar
CREATE POLICY "allow_update" ON checklist
  FOR UPDATE USING (auth.role() = 'authenticated') 
  WITH CHECK (auth.role() = 'authenticated');

-- Política DELETE: Todos los usuarios autenticados pueden eliminar
CREATE POLICY "allow_delete" ON checklist
  FOR DELETE USING (auth.role() = 'authenticated');

-- PASO 6: Verificar
SELECT 'Tabla configurada con RLS' as status, COUNT(*) as registros FROM checklist;
