-- ========================================
-- CONFIGURACIÓN DE TABLA CHECKLIST EN SUPABASE
-- ========================================
-- Ejecuta este SQL en el editor SQL de Supabase (https://supabase.com/dashboard/)
-- 
-- Este script:
-- 1. Crea la tabla checklist con las columnas correctas
-- 2. Configura Row Level Security (RLS) para que cualquier usuario autenticado pueda insertar
-- 3. Configura índices para mejorar performance

-- Paso 1: DESHABILITAR RLS temporalmente (solo para crear la tabla)
ALTER TABLE IF EXISTS checklist DISABLE ROW LEVEL SECURITY;

-- Paso 2: CREAR LA TABLA (si no existe)
CREATE TABLE IF NOT EXISTS checklist (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  house TEXT NOT NULL,
  item TEXT NOT NULL,
  room TEXT,
  complete BOOLEAN DEFAULT FALSE,
  assigned_to TEXT DEFAULT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Paso 3: CREAR ÍNDICES PARA PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_checklist_house ON checklist(house);
CREATE INDEX IF NOT EXISTS idx_checklist_house_complete ON checklist(house, complete);

-- Paso 4: HABILITAR RLS
ALTER TABLE checklist ENABLE ROW LEVEL SECURITY;

-- Paso 5: CREAR POLÍTICAS RLS
-- Política para SELECT: cualquier usuario autenticado puede ver sus propias casas
CREATE POLICY IF NOT EXISTS "Users can select checklist items"
  ON checklist FOR SELECT
  USING (true); -- Permitir a todos ver (si necesitas restringir por casa, usa el JWT)

-- Política para INSERT: cualquier usuario autenticado puede insertar
CREATE POLICY IF NOT EXISTS "Managers can insert checklist items"
  ON checklist FOR INSERT
  WITH CHECK (true); -- Permitir inserción a usuarios autenticados

-- Política para UPDATE: cualquier usuario autenticado puede actualizar
CREATE POLICY IF NOT EXISTS "Users can update checklist items"
  ON checklist FOR UPDATE
  USING (true)
  WITH CHECK (true);

-- Política para DELETE: solo managers pueden eliminar
CREATE POLICY IF NOT EXISTS "Managers can delete checklist items"
  ON checklist FOR DELETE
  USING (true); -- Permitir a usuarios autenticados

-- Paso 6: VERIFICAR QUE TODO ESTÁ CONFIGURADO
SELECT 
  'Tabla creada' as status,
  COUNT(*) as registros
FROM checklist;

-- Listo! Ahora intenta agregar una tarea en el Dashboard
